# -*- coding: utf-8 -*-
"""Canopy_Covers.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1B2drp2V390b0y36rXtyfjEE8VnYzsqKX
"""

import pandas as pd
import geopandas as gpd
import matplotlib.pyplot as plt
import folium
import branca.colormap as cm

gdf = gpd.read_file("/content/erdo.json")

gdf.columns

gdf.head()

gdf.plot()

gdf.shape

gdf.info()

gdf.crs

gdf['DN'].hist(bins=30)

ax = gdf.plot(
    column= 'DN',   # ← replace with the real column name
    legend=True,
    cmap="viridis",              # try: "plasma", "YlOrRd", "RdYlGn", "Blues", etc.
    edgecolor="none",
    linewidth=0.3,
    figsize=(12, 10),
    missing_kwds={"color": "lightgrey"}  # how to show missing values
)

plt.title("Map colored by your_column_name", fontsize=14)
plt.axis("off")                  # hide x/y axes (looks cleaner for maps)
plt.tight_layout()
plt.show()

# calculate bounds
bounds = gdf.total_bounds

bounds

# Calculate center point and bounds for dynamic map framing
center_lat = (bounds[1] + bounds[3]) /2
center_lon = (bounds[0] + bounds[2]) /2

center_lat,center_lon

# Create a diverging colormap (Red for negative/decline, Blue for positive/growth)
min_dn = float(gdf['DN'].min())
max_dn = float(gdf['DN'].max())

min_dn,max_dn

colormap = cm.LinearColormap(
    colors=["#d73027", "#f46d43", "#fdae61", "#fee090", "#e0f3f8", "#4575b4"],
    index=[min_dn,
           min_dn + (max_dn + min_dn) *0.2,
           min_dn + (max_dn - min_dn) * 0.4,
           min_dn + (max_dn - min_dn) * 0.6,
           min_dn + (max_dn - min_dn) * 0.8,
           max_dn,
           ],
    vmin=min_dn,
    vmax=max_dn,
    caption="Density Change (DN)",
)

# 5. Initialize Folium Map centered on features
m = folium.Map(
    location=[center_lat, center_lon],
    zoom_start=16,
    tiles="CartoDB positron",  # Clean, minimalist light basemap
)

# Add alternative basemaps
folium.TileLayer("OpenStreetMap", name="OpenStreetMap").add_to(m)
folium.TileLayer("CartoDB dark_matter", name="Dark Basemap").add_to(m)

# 6. Add Interactive GeoJSON Layer with Tooltips and Hover Highlights
style_function = lambda feature: {
    "fillColor": colormap(feature["properties"]["DN"]),
    "color": "none",  # border color
    "weight": 0.8,  # border thickness
    "fillOpacity": 0.75,
}
highlight_function = lambda feature: {
    "fillColor": "#ffff00",  # bright yellow highlight on hover
    "color": "#000000",
    "weight": 2.5,
    "fillOpacity": 0.9,
}

geojson_layer = folium.GeoJson(
    gdf,
    name="Density Change Grids",
    style_function=style_function,
    highlight_function=highlight_function,
    tooltip=folium.GeoJsonTooltip(
        fields=["fid", "DN"],
        aliases=["Grid ID:", "Density Change (DN):"],
        localize=True,
        sticky=True,
        style="""
            background-color: #2b2b2b;
            color: #ffffff;
            font-family: Arial, sans-serif;
            font-size: 13px;
            padding: 8px;
            border-radius: 4px;
        """,
    ),
).add_to(m)

# 7. Add Colormap Legend and Layer Control to map
colormap.add_to(m)
folium.LayerControl(position="topright").add_to(m)

# Fit map bounds to encompass all grid features tightly
m.fit_bounds([[bounds[1], bounds[0]], [bounds[3], bounds[2]]])

# Render map in Google Colab
m

